### ISSUE TITLE
Assistance Required for EDI Process Setup on Odoo

### ISSUE THREAD

**Issue by Hbohry** [OCA/edi#1079] opened 2024-12-02 13:03 UTC
We are currently facing some difficulties in setting up the EDI process on Odoo and need your assistance to move forward. 

Here is what we've done so far:

To implement the EDI process, we have cloned all the modules into the EDI Framework repository.

We have watched the OCA Days videos on EDI (2021, 2022, and 2023).

Our goal is to create a quote automatically on Odoo from FTP, and we believe the EDI modules should handle this task.

We have followed these steps:

- Configuration of the FTP server.

- Configuration of EDI Backend and EDI Backend Type.

- Configuration of Exchange Type and its component:

```
components:
    process:
        usage: input.process.sale.order
sale_order:
        confirm_order: true
```

- Manual execution of the cron: "EDI exchange check input sync".

However, we are currently stuck and do not know what to do next to make the import work.

Could you please guide us on how to proceed or provide any assistance to help us resolve this issue?

Below you can find some details explaining our setup :

**FTP server configuration** 
![FTP](https://github.com/user-attachments/assets/5be27da6-76dc-404e-8777-9f0838e43c45)

**Configuration EDI BACKEND :**
![backend](https://github.com/user-attachments/assets/67df4e16-51f1-4e0f-9fc3-8c3da4d2bbf4)
![backen-type](https://github.com/user-attachments/assets/704c2f78-ab53-43f3-bcaa-892a40daff21)

**Configuration EDI Exchange type :**
![exchange-type](https://github.com/user-attachments/assets/08694f0c-1de0-4c31-a74e-c754895a043f)
![component](https://github.com/user-attachments/assets/c28da75d-5e10-4c49-ab7b-1c02c88d0694)
![rule](https://github.com/user-attachments/assets/2413b2ab-35fa-4a8e-9d44-2a5f35840918)

**All  the resulting job queues are failed :**
![queue-job](https://github.com/user-attachments/assets/bcd43d1c-4115-41a9-9476-46a596f4824f)

In addition to that , all the exchanges records created are either pending or doesn't have any files 
![EDI-exchange](https://github.com/user-attachments/assets/edb4b2c2-bed4-40d7-81d8-b14dd3e2bed2)

Thank you very much for your support.

**Comment by simahawk** [comment] 2024-12-02 15:50
Hello,
1st: Odoo version?

**Comment by Hbohry** [comment] 2024-12-03 07:53
Good morning ,
Odoo version : 16 enterprise
________________________________

**Comment by simahawk** [comment] 2024-12-05 05:58
Looks like a duplicate of https://github.com/OCA/edi-framework/issues/121 and since we are on 16.0 I'd keep the other one.

**Closed as completed by simahawk** 2024-12-05 05:58 UTC
Labels: question
